# Site settings
title: Slow School
email: oscar@slowschool.se
description: > #Slow School - för ett långsammare och mentalt starkare Sverige.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Hem', '/', 'fa-home']
  About : ['Uppdraget', '/about', 'fa-bullhorn']
  Home_Alt : ['Inspiration', '/inpiration', 'fa-child']
  Produkter : ['Produkter', '/produkter/', 'fa-fire']
  Contact : ['Kontakta', '/contact', 'fa-plane']
  Founder : ['OT', '/author/tege', 'fa-user']
  Author : ['Mindful Slowfoot', '/author/slowfoot', 'fa-user']
single_footer: '<p>För ett långsammare och mentalt starkare Sverige.<a href="/">senaste inlägg</a></p>'
footer_links:
    About: ['Om', '/about']
    Writer: ['Slow School', '/about']
gems:
  - jekyll-seo-tag


#Build settings
markdown: kramdown
